.TH cronical 1 "8 May 2020"
.SH NAME
cronical - a reminder to create a regular appointment with your cron tasks. 
.SH DESCRIPTION
Create ical or supported calendar formatted objects from cron entries. 
.SH SEE ALSO
cron.
crontab.
.SH AUTHOR
ross-spencer <all.along.the.watchtower2001+github@gmail.com>
.SH COPYRIGHT
GNU General Public License v3.0
